name: github-actions-example
on: [push]
jobs:
  run-boozang-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g boozang
      - name: Run headless test with Boozang
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./ #optional
          run: boozang "http://staging-be.boozang.com/extension?token=9b1cef55504467b6436ab2aaffe93f926009e593b0700759eb43fb8c&env=0#6009e593b0700759eb43fb8c/master/m35/t1/run"
      - run: npm install multiple-cucumber-html-reporter --save-dev && node reporter.js && ls -l && ls -l json && ls -l public && pwd
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'