name: github-actions-example
on: [push]
jobs:
  run-boozang-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g boozang
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./ #optional
          run: boozang "https://google.com"
